[package]
name = "galm"
version = "0.0.4"
license = "MIT"
authors = ["awrznc"]
edition = "2018"
description = "GalM is pattern matching library."
readme = "README.md"
build = "./src/build.rs"


[dependencies]
